name: Regression End-to-End tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Config Environment Variable
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI_STAGING }}" >> $GITHUB_ENV
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            start: npm run dev
            wait-on: 'http://localhost:3000'
            command-prefix: npx cross-env CI=true
            command: npm run cy:run:regression
